"""Add mapping_configs table

Revision ID: 7f3d8e900127
Revises: 002
Create Date: 2026-04-17 19:16:05.111126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f3d8e900127'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mapping_config_name', 'mapping_configs', ['name'], unique=False)
    op.create_index('ix_mapping_config_owner', 'mapping_configs', ['owner_id'], unique=False)
    
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('action_type',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.Enum('folder_create', 'folder_rename', 'folder_delete', 'ticket_assign', 'ticket_unassign', 'ticket_bulk_assign', 'ticket_create', 'ticket_delete', 'ticket_classify', 'ticket_escalate', 'ticket_override', 'pattern_alert_create', 'pattern_alert_dismiss', 'pattern_alert_snooze', 'pattern_alert_acknowledge', 'model_promote', 'webhook_delivery_failed', 'retrain_skipped_concurrent', name='audit_action_enum'),
               existing_nullable=False)

    with op.batch_alter_table('ticket_embeddings', schema=None) as batch_op:
        batch_op.drop_index('ix_embedding_ticket')

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_repeated_issue', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.alter_column('ticket_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_tickets_ticket_number'), ['ticket_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_ticket_number'), table_name='tickets')
    op.alter_column('tickets', 'ticket_number',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('tickets', 'is_repeated_issue')
    op.create_index('ix_embedding_ticket', 'ticket_embeddings', ['ticket_id'], unique=False)
    op.alter_column('audit_log', 'action_type',
               existing_type=sa.Enum('folder_create', 'folder_rename', 'folder_delete', 'ticket_assign', 'ticket_unassign', 'ticket_bulk_assign', 'ticket_create', 'ticket_delete', 'ticket_classify', 'ticket_escalate', 'ticket_override', 'pattern_alert_create', 'pattern_alert_dismiss', 'pattern_alert_snooze', 'pattern_alert_acknowledge', 'model_promote', 'webhook_delivery_failed', 'retrain_skipped_concurrent', name='audit_action_enum'),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    op.drop_index('ix_mapping_config_owner', table_name='mapping_configs')
    op.drop_index('ix_mapping_config_name', table_name='mapping_configs')
    op.drop_table('mapping_configs')
    # ### end Alembic commands ###
